### PR TITLE
Refactor/intermediate controls

### PR DESCRIPTION
**Pull request by astingen**
This is a pretty major refactor.

When named controls or components are instantiated, the module lazy loads them from the core. The core looks up the name, and returns the control/component intermediary if it exists already. If it doesn't exist, it creates it, adds it to the collection, and returns it. Multiple modules using the same control or component all receive the same intermediary.

Modules then subscribe to the event on the intermediary. When feedback is received, the control/component intermediary is looked up by name in the collection (using a dictionary with O(1) lookup time). The feedback event on the intermediary is fired, and all subscribed modules receive the update and act accordingly.

Controls on Named Components work in a similar manor, and also have their own intermediary / lazy load process.

Many of the control names are now generated by the `ControlNameUtils` static class, to reduce re-use of hard-coded strings.

I added  `QsysMatrixMixerOutputAllCrosspoints` - this is to allow for mute/unmute of all the inputs of a specified output on a matrix mixer.

There are a few things that still need to be cleaned up, eventually (but I'm not going to do now):
1) A few named components don't use the intermediaries for feedback. See `QsysCamera`, `QsysPotsController`, and `QsysRoomCombiner`.
2) There are a lot of places that still use hard-coded strings in the modules for the control names - these should be moved to `ControlNameUtils`.

### CODE REVIEW

**Comment by astingen** [comment]
This is as far as I'm planning to take this branch at the moment, unless there are specific things you want changed ahead of a merge.

**Comment by MatKlucznyk** [comment]
> This is as far as I'm planning to take this branch at the moment, unless there are specific things you want changed ahead of a merge.

Thank you for this! I've had a chance to quickly review. As soon as I can, I will fully review but so far looks amazing.

**Review by MatKlucznyk — COMMENTED** [review]
There are a couple of modules that are currently not working.

Qsys Matrix Mixer Output All Crosspoints
Qsys Room Combiner
Qsys Snapshot Controller
Qsys Camera

It looks like most of them are related to controls that require a range ie. Total snapshots

Let me know if they are working for you. If not then hopefully we can sort that out because you've done what I have wanted to do for a while :)

**Comment by PeterScream** [comment]
Oh dear that's something I desperately need ...
shall I use prev builds or sponsor a big crate of beer for someone? :))

**Comment by MatKlucznyk** [comment]
> Oh dear that's something I desperately need ...
> shall I use prev builds or sponsor a big crate of beer for someone? :))

You can continue to use the master branch, I haven’t merged this branch yet.

**Comment by astingen** [comment]
> There are a couple of modules that are currently not working.
> 
> Qsys Matrix Mixer Output All Crosspoints
> Qsys Room Combiner
> Qsys Snapshot Controller
> Qsys Camera
> 


I'll check it out tomorrow and let you know

**Comment by PeterScream** [comment]
and just found out that need snapshots.

**Comment by astingen** [comment]
> Many thanks, 
> just found out that need snapshots. 
> 

As Mat said, you can use the release version for now. Unless you need more than 8 snapshots in the same bank, or have lots of controls you're using (for reference, I've got 7,000+, which prompted this refactor), you will be fine with current release.

**Comment by PeterScream** [comment]
definetly less than 8, thats great, many thanks for a promt reply you guys are awesome

**Comment by astingen** [comment]
> There are a couple of modules that are currently not working.
> 
> Qsys Matrix Mixer Output All Crosspoints
> Qsys Room Combiner
> Qsys Snapshot Controller
> Qsys Camera
> 

Ok, updated. It was a null ref exception being thrown in a OnCoreAdded event handler, which prevented the subsequent handlers from being called.

**Comment by astingen** [comment]
Related: Is your TCP client library public? I'm getting stuff printed to the console every time it sends something:

> TCP_Client ID =main Sending command

**Review by MatKlucznyk — APPROVED** [review]

**Pull request merged**
